version: "3.9"
services:
  web:
    build:
      target: dev
      context: ./web/
    image: sontek/web:dev
    ports:
      - "3000:3000"
    volumes:
      - "./web/:/srv/"
      - "./shared_volume/web:/srv/dist/"
      # overwrite the volume to still keep
      # node_modules in the container
      - "/srv/node_modules"

  api:
    build:
      target: dev
      context: ./api/
    image: sontek/api:dev
    environment:
      - STK_HOSTNAME=sontek.local
    ports:
      - "8000:8000"
    volumes:
      - "./api/:/srv"
      - "./shared_volume/blog:/srv/output/"

  nginx:
    build:
      context: ./nginx/
    image: sontek/nginx:dev
    ports:
      - "80:80"
      - "443:443"
    environment:
      - STK_HOSTNAME=sontek.local
      - STK_API_HOST=api
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf.template"
      - "./shared_volume/:/usr/share/nginx/html/"
    depends_on:
      - web

