version: "3.9"
services:
  stkapi:
    image: sontek/stkapi

  stknginx:
    image: sontek/stknginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - STK_API_HOST=stkapi
      - STK_HOSTNAME=sontek.net
    depends_on:
      - stkapi
