version: "3.9"
services:
  stkweb:
    build:
      target: dev
      context: ./web/

    volumes:
      - "./web/:/srv"

  stknginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
    environment:
      - STK_WEB_HOST=stkweb
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf.template"
    depends_on:
      - stkweb

