vm_url = ENV.fetch('VAGRANT_IMAGE_PATH', 'https://dl.dropboxusercontent.com/u/31435348/fedora20.box')

Vagrant.configure("2") do |config|
    config.vm.box = "sontek_net"
    config.vm.box_url = vm_url
    config.vm.network :private_network, ip: "192.168.21.253"
    config.ssh.forward_agent = true

    config.vm.provider :virtualbox do |vb|
        # boot with headless mode
        vb.gui = false

        # Use VBoxManage to customize the VM. For example to change memory:
        vb.customize [
          "modifyvm", :id, "--memory", "2048", "--cpus", "2",
        ]

    end

    # if you have multiple
    # Share an additional folder to the guest VM. The first argument is the
    # folder on the host, second is the folder on the guest.
    config.vm.synced_folder 'src/', '/opt/src', :nfs => false
end
