name: deploy
on:
  push:
    branches: main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️  The workflow is now ready to test your code on the runner."
      - name: Install just
        shell: bash
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to $HOME/.local/bin
          echo $HOME/.local/bin >> $GITHUB_PATH
      - run: echo "🍕Configure git so we can push to gh-pages branch"
      - name: Setup the git credentials
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

      - name: Deploy to production
        run: |
          just fe-deploy-prod
      - run: echo "🍏 This job's status is ${{ job.status }}."


